-- =============================================================================
-- Oracle XE DDL — Stripe Integration Schema
-- Re-runnable: drop guards at the top, creates at the bottom.
-- Run as the schema owner (e.g. STRIPE_APP).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. DROP in reverse-dependency order
-- ---------------------------------------------------------------------------

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STRIPE_WEBHOOK_EVENTS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUBSCRIPTION_PLANS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STRIPE_SUBSCRIPTIONS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STRIPE_SETUP_INTENTS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STRIPE_PAYMENT_INTENTS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STRIPE_PAYMENT_METHODS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STRIPE_CUSTOMERS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE APP_USERS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ---------------------------------------------------------------------------
-- 2. APP_USERS
-- ---------------------------------------------------------------------------

CREATE TABLE APP_USERS (
  ID              VARCHAR2(36)   NOT NULL,
  EMAIL           VARCHAR2(255)  NOT NULL,
  PASSWORD_HASH   VARCHAR2(255)  NOT NULL,
  CREATED_AT      TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  UPDATED_AT      TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_APP_USERS PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UQ_APP_USERS_EMAIL ON APP_USERS (EMAIL);

-- ---------------------------------------------------------------------------
-- 3. STRIPE_CUSTOMERS
-- ---------------------------------------------------------------------------

CREATE TABLE STRIPE_CUSTOMERS (
  ID                   VARCHAR2(36)   NOT NULL,
  STRIPE_CUSTOMER_ID   VARCHAR2(50)   NOT NULL,
  EMAIL                VARCHAR2(255)  NOT NULL,
  NAME                 VARCHAR2(255),
  PHONE                VARCHAR2(50),
  METADATA             CLOB,
  IDEMPOTENCY_KEY      VARCHAR2(255),
  USER_ID              VARCHAR2(36),
  IS_DELETED           NUMBER(1)      DEFAULT 0 NOT NULL,
  CREATED_AT           TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  UPDATED_AT           TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_STRIPE_CUSTOMERS     PRIMARY KEY (ID),
  CONSTRAINT FK_SC_USER_ID           FOREIGN KEY (USER_ID) REFERENCES APP_USERS (ID),
  CONSTRAINT CHK_SC_IS_DELETED       CHECK (IS_DELETED IN (0, 1))
);

CREATE UNIQUE INDEX UQ_STRIPE_CUSTOMERS_STRIPE_ID ON STRIPE_CUSTOMERS (STRIPE_CUSTOMER_ID);

-- ---------------------------------------------------------------------------
-- 4. STRIPE_PAYMENT_METHODS
-- ---------------------------------------------------------------------------

CREATE TABLE STRIPE_PAYMENT_METHODS (
  ID                   VARCHAR2(36)   NOT NULL,
  STRIPE_PM_ID         VARCHAR2(100)  NOT NULL,
  TYPE                 VARCHAR2(50)   NOT NULL,
  LAST4                VARCHAR2(4),
  BRAND                VARCHAR2(50),
  EXP_MONTH            NUMBER(2),
  EXP_YEAR             NUMBER(4),
  FINGERPRINT          VARCHAR2(100),
  DETAILS              CLOB,
  BILLING_DETAILS      CLOB,
  CARD_WALLET_TYPE     VARCHAR2(50),
  COUNTRY              VARCHAR2(2),
  FUNDING              VARCHAR2(20),
  CUSTOMER_ID          VARCHAR2(36)   NOT NULL,
  IS_DEFAULT           NUMBER(1)      DEFAULT 0 NOT NULL,
  CREATED_AT           TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  UPDATED_AT           TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_STRIPE_PAYMENT_METHODS   PRIMARY KEY (ID),
  CONSTRAINT FK_SPM_CUSTOMER_ID          FOREIGN KEY (CUSTOMER_ID) REFERENCES STRIPE_CUSTOMERS (ID),
  CONSTRAINT CHK_SPM_IS_DEFAULT          CHECK (IS_DEFAULT IN (0, 1))
);

CREATE UNIQUE INDEX UQ_STRIPE_PM_STRIPE_ID ON STRIPE_PAYMENT_METHODS (STRIPE_PM_ID);
CREATE INDEX IDX_SPM_CUSTOMER_ID ON STRIPE_PAYMENT_METHODS (CUSTOMER_ID);

-- ---------------------------------------------------------------------------
-- 5. STRIPE_PAYMENT_INTENTS
-- ---------------------------------------------------------------------------

CREATE TABLE STRIPE_PAYMENT_INTENTS (
  ID                     VARCHAR2(36)    NOT NULL,
  STRIPE_PI_ID           VARCHAR2(100)   NOT NULL,
  AMOUNT                 NUMBER(15, 0)   NOT NULL,
  CURRENCY               VARCHAR2(3)     NOT NULL,
  STATUS                 VARCHAR2(50)    NOT NULL,
  CLIENT_SECRET          VARCHAR2(500)   NOT NULL,
  CUSTOMER_ID            VARCHAR2(36)    NOT NULL,
  STRIPE_PM_ID           VARCHAR2(100),
  IDEMPOTENCY_KEY        VARCHAR2(255),
  METADATA               CLOB,
  DESCRIPTION            VARCHAR2(4000),
  ERROR_CODE             VARCHAR2(100),
  ERROR_DECLINE_CODE     VARCHAR2(100),
  ERROR_MESSAGE          VARCHAR2(4000),
  SETUP_FUTURE_USAGE     VARCHAR2(20),
  NEXT_ACTION            CLOB,
  PAYMENT_METHOD_TYPES   VARCHAR2(500),
  AMOUNT_RECEIVED        NUMBER(15, 0),
  AMOUNT_CAPTURABLE      NUMBER(15, 0),
  RECEIPT_EMAIL          VARCHAR2(255),
  STATEMENT_DESCRIPTOR   VARCHAR2(22),
  LIVEMODE               NUMBER(1)       DEFAULT 0 NOT NULL,
  CREATED_AT             TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  UPDATED_AT             TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_STRIPE_PAYMENT_INTENTS   PRIMARY KEY (ID),
  CONSTRAINT FK_SPI_CUSTOMER_ID          FOREIGN KEY (CUSTOMER_ID) REFERENCES STRIPE_CUSTOMERS (ID),
  CONSTRAINT CHK_SPI_LIVEMODE            CHECK (LIVEMODE IN (0, 1))
);

CREATE UNIQUE INDEX UQ_STRIPE_PI_STRIPE_ID ON STRIPE_PAYMENT_INTENTS (STRIPE_PI_ID);
CREATE INDEX IDX_SPI_CUSTOMER_ID ON STRIPE_PAYMENT_INTENTS (CUSTOMER_ID);

-- ---------------------------------------------------------------------------
-- 6. STRIPE_SETUP_INTENTS
-- ---------------------------------------------------------------------------

CREATE TABLE STRIPE_SETUP_INTENTS (
  ID                     VARCHAR2(36)   NOT NULL,
  STRIPE_SI_ID           VARCHAR2(100)  NOT NULL,
  STATUS                 VARCHAR2(50)   NOT NULL,
  CLIENT_SECRET          VARCHAR2(500)  NOT NULL,
  CUSTOMER_ID            VARCHAR2(36)   NOT NULL,
  STRIPE_PM_ID           VARCHAR2(100),
  IDEMPOTENCY_KEY        VARCHAR2(255),
  METADATA               CLOB,
  DESCRIPTION            VARCHAR2(4000),
  PAYMENT_METHOD_TYPES   VARCHAR2(500),
  USAGE                  VARCHAR2(20),
  LAST_SETUP_ERROR       CLOB,
  NEXT_ACTION            CLOB,
  LIVEMODE               NUMBER(1)      DEFAULT 0 NOT NULL,
  CREATED_AT             TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  UPDATED_AT             TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_STRIPE_SETUP_INTENTS   PRIMARY KEY (ID),
  CONSTRAINT FK_SSI_CUSTOMER_ID        FOREIGN KEY (CUSTOMER_ID) REFERENCES STRIPE_CUSTOMERS (ID),
  CONSTRAINT CHK_SSI_LIVEMODE          CHECK (LIVEMODE IN (0, 1))
);

CREATE UNIQUE INDEX UQ_STRIPE_SI_STRIPE_ID ON STRIPE_SETUP_INTENTS (STRIPE_SI_ID);
CREATE INDEX IDX_SSI_CUSTOMER_ID ON STRIPE_SETUP_INTENTS (CUSTOMER_ID);

-- ---------------------------------------------------------------------------
-- 7. STRIPE_SUBSCRIPTIONS
-- ---------------------------------------------------------------------------

CREATE TABLE STRIPE_SUBSCRIPTIONS (
  ID                     VARCHAR2(36)   NOT NULL,
  STRIPE_SUB_ID          VARCHAR2(100)  NOT NULL,
  STATUS                 VARCHAR2(50)   NOT NULL,
  CURRENT_PERIOD_START   TIMESTAMP,
  CURRENT_PERIOD_END     TIMESTAMP,
  CANCEL_AT_PERIOD_END   NUMBER(1)      DEFAULT 0 NOT NULL,
  TRIAL_END              TIMESTAMP,
  TRIAL_START            TIMESTAMP,
  STRIPE_PRICE_ID        VARCHAR2(100)  NOT NULL,
  DEFAULT_PM_ID          VARCHAR2(100),
  CUSTOMER_ID            VARCHAR2(36)   NOT NULL,
  METADATA               CLOB,
  CREATED_AT             TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  UPDATED_AT             TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_STRIPE_SUBSCRIPTIONS      PRIMARY KEY (ID),
  CONSTRAINT FK_SSUB_CUSTOMER_ID          FOREIGN KEY (CUSTOMER_ID) REFERENCES STRIPE_CUSTOMERS (ID),
  CONSTRAINT CHK_SSUB_CANCEL_PERIOD_END   CHECK (CANCEL_AT_PERIOD_END IN (0, 1))
);

CREATE UNIQUE INDEX UQ_STRIPE_SUB_STRIPE_ID ON STRIPE_SUBSCRIPTIONS (STRIPE_SUB_ID);
CREATE INDEX IDX_SSUB_CUSTOMER_ID ON STRIPE_SUBSCRIPTIONS (CUSTOMER_ID);

-- ---------------------------------------------------------------------------
-- 8. STRIPE_WEBHOOK_EVENTS
-- ---------------------------------------------------------------------------

CREATE TABLE STRIPE_WEBHOOK_EVENTS (
  ID               VARCHAR2(36)    NOT NULL,
  STRIPE_EVENT_ID  VARCHAR2(100)   NOT NULL,
  EVENT_TYPE       VARCHAR2(100)   NOT NULL,
  PAYLOAD          CLOB            NOT NULL,
  STATUS           VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
  ERROR_MESSAGE    VARCHAR2(4000),
  RETRY_COUNT      NUMBER          DEFAULT 0 NOT NULL,
  PROCESSED_AT     TIMESTAMP,
  CREATED_AT       TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  UPDATED_AT       TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_STRIPE_WEBHOOK_EVENTS   PRIMARY KEY (ID),
  CONSTRAINT CHK_SWE_STATUS             CHECK (STATUS IN ('pending', 'processed', 'failed', 'skipped'))
);

CREATE UNIQUE INDEX UQ_STRIPE_WE_STRIPE_ID ON STRIPE_WEBHOOK_EVENTS (STRIPE_EVENT_ID);
CREATE INDEX IDX_SWE_STATUS ON STRIPE_WEBHOOK_EVENTS (STATUS);

-- ---------------------------------------------------------------------------
-- 9. SUBSCRIPTION_PLANS
-- ---------------------------------------------------------------------------

CREATE TABLE SUBSCRIPTION_PLANS (
  ID                VARCHAR2(36)    NOT NULL,
  STRIPE_PRICE_ID   VARCHAR2(100)   NOT NULL,
  STRIPE_PRODUCT_ID VARCHAR2(100)   NOT NULL,
  NAME              VARCHAR2(255)   NOT NULL,
  DESCRIPTION       VARCHAR2(4000),
  AMOUNT            NUMBER(15, 0)   NOT NULL,
  CURRENCY          VARCHAR2(3)     DEFAULT 'usd' NOT NULL,
  INTERVAL_TYPE     VARCHAR2(20)    NOT NULL,
  INTERVAL_COUNT    NUMBER          DEFAULT 1 NOT NULL,
  IS_ACTIVE         NUMBER(1)       DEFAULT 1 NOT NULL,
  CREATED_AT        TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  UPDATED_AT        TIMESTAMP       DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SUBSCRIPTION_PLANS   PRIMARY KEY (ID),
  CONSTRAINT CHK_SP_IS_ACTIVE        CHECK (IS_ACTIVE IN (0, 1))
);

CREATE UNIQUE INDEX UQ_SP_STRIPE_PRICE_ID ON SUBSCRIPTION_PLANS (STRIPE_PRICE_ID);

-- =============================================================================
-- End of schema
-- =============================================================================
